GET http://localhost:3000/posts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY2MzExMTAyMiwiZXhwIjoxNjYzMTExMDM3fQ.5zva8er_pcpNotOrhO9p2GsmTdmrk0IPEDp6LMKPLRw

###

DELETE http://localhost:4000/logout
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiSmltIiwiaWF0IjoxNTY4NzU5OTIyfQ.RT6wszuCeFLwC_6ksmNMIELxiC5s-uRivfRxyZof5ag"
}

###

POST http://localhost:4000/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuYW1lIjoiS3lsZSIsImlhdCI6MTY2MzExMDk4OX0.IINit3WNHDEEeYpkCN08fuHoXgLMyRAFe2yzKtynmQ8"
}

###

POST http://localhost:4000/login
Content-Type: application/json

{
  "username": "Kyle"
}